global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: api_core
    tls_config:
      insecure_skip_verify: true
    scheme: https
    static_configs:
      - targets: ["api_core:5001"]
  - job_name: api_notifications
    tls_config:
      insecure_skip_verify: true
    scheme: https
    static_configs:
      - targets: ["api_notifications:5003"]
