version: "3.4"

networks:
  app:
  logs:

services:
  articlib.articles.api:
    image: ${DOCKER_REGISTRY-}articlibarticlesapi
    build:
      context: .
      dockerfile: Articles/Source/Articlib.Articles.Api/Dockerfile
    volumes:
      - /var/log:/var/log
    networks:
      - app

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logs

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log/promtail:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logs

  grafana:
    build:
        context: Services/Grafana
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - logs
