name: articlib-identity-ci

on:
  push:
    branches-ignore:
      - "private/**"
  pull_request:
    branches-ignore:
      - "private/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: docker build ./Articlib -f ./Articlib/Users/Source/Articlib.Users.Api/Dockerfile --target test

      - name: Build
        run: docker build ./Articlib -f ./Articlib/Users/Source/Articlib.Users.Api/Dockerfile --tag articlib-users:ci-$(date +%s)
