name: articlib-core-ci

on:
  push:
    branches-ignore:
      - "private/**"
  pull_request:
    branches-ignore:
      - "private/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        if: ${{ false }}
        run: docker build ./Articlib -f ./Articlib/Core/Source/Articlib.Core.Api/Dockerfile --target test

      - name: Build
        run: docker build ./Articlib -f ./Articlib/Core/Source/Articlib.Core.Api/Dockerfile --tag articlib-core:ci-$(date +%s)
