name: articlib-core-ci

on:
  push:
    branches-ignore:
      - "private/**"
  pull_request:
    branches-ignore:
      - "private/**"
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup-variables
        run: > 
          echo "VERSION=1.0.0-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV &&
          echo "PACKAGE_NAME=articlib.jfrog.io/dev-docker-local/debug/core:ci-$ENV_VERSION" >> $GITHUB_ENV
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: test
        run: docker build ./Articlib -f ./Articlib/Core/Source/Articlib.Core.Api/articlib-core.dockerfile --target test
      - name: build
        run: >
          docker build ./Articlib
          -f ./Articlib/Core/Source/Articlib.Core.Api/articlib-core.dockerfile
          -t $PACKAGE_NAME
          -l articlib.environment=dev articlib.configuration=debug articlib.branch=$GITHUB_REF_NAME
          articlib.commit=$GITHUB_SHA articlib.workflow=$GITHUB_WORKFLOW articlib.version=$VERSION
      - name: docker-login
        run: docker login articlib.jfrog.io -u service-github -p ${{secrets.ARTIFACTORY_TOKEN}}
      - name: docker-push
        run: docker push $PACKAGE_NAME
      
