name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: docker build ./Articlib -f ./Articlib/Articles/Source/Articlib.Articles.Api/Dockerfile --target test

      - name: Build
        run: docker build ./Articlib -f ./Articlib/Articles/Source/Articlib.Articles.Api/Dockerfile --tag articles:$(date +%s)
