name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Docker compose
        run: docker-compose  -f "./Articlib/docker-compose.yml" -f "./Articlib/docker-compose.override.yml" -p articlib-ci --ansi never build
