name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build . --file ./Articlib/Articles/Source/Articlib.Articles.Api/Dockerfile --tag my-image-name:$(date +%s)
